# 指明cocoapod使用的源，可以多源
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/rongfei3380/Specs.git'
#source 'https://github.com/aliyun/aliyun-specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace '../newProject.xcworkspace'

target 'newProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newProject
  pod 'CFFoundation', :path => 'Vendor/CFFoundation'
  pod 'CFNetworkKit', :path => 'Vendor/CFNetworkKit'
  
  target 'newProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'newProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
